# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go/Go+
      uses: goplus/setup-goplus@v1.1.1
      with:
        go-version: "1.18"
        gop-version: "main"

    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev libasound2-dev libopenal-dev
      if: ${{ runner.os == 'Linux' }}

    - name: Build
      run: go build -v ./...

    - name: GenGo
      run: gop go ./...
